Train:
  batch_size: 128
  learning_rate: 0.00001
  epochs: 10

network:
  model: VisionTransformer
  d_model: 512 
  nhead: 8 
  dim_feedforward: 2048 
  num_layers: 4
  dropout: 0.1

debug:
  # image_analysis: [1, 1, 1]
  image_analysis: [0, 0, 0]

data:
  beta: .9999999
  weight_decay: 0.000001

loss:
  loss_type: CE