Train:
  batch_size: 128
  learning_rate: 0.0001
  epochs: 30

network:
  # model: CNN
  model: split_CNN
  vocab_dim: 13

debug:
  # image_analysis: [1, 1, 1]
  image_analysis: [0, 0, 0]

data:
  beta: .9999999
  weight_decay: 0.000001

loss:
  loss_type: CE